/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foro;

import com.sun.awt.AWTUtilities;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.MulticastSocket;
import java.util.Arrays;
import static javafx.scene.control.ButtonType.OK;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author irving-mac
 */
public class registro extends javax.swing.JFrame {

    ClientUnicast ClientUnicast = new ClientUnicast(this,null,null);
    
    
    int x,y;
    public registro() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        ClientUnicast.start();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JTextField();
        lblP = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblPassword = new javax.swing.JPasswordField();
        lblSesion = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 130));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 230, 50));

        lblP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pass.png"))); // NOI18N
        getContentPane().add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        lblU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usr.png"))); // NOI18N
        getContentPane().add(lblU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 210, 50));

        lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 230, 50));

        lblSesion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblSesion.setText("Tengo una cuenta");
        lblSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSesionMouseClicked(evt);
            }
        });
        getContentPane().add(lblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, 20));

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wall2.png"))); // NOI18N
        lblLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblLoginMouseDragged(evt);
            }
        });
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoginMousePressed(evt);
            }
        });
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-870, -430, 1300, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = lblUsername.getText();
        String pass = lblPassword.getText();
        if(name.equals("") || name.length()<4){
            JOptionPane.showMessageDialog(this, "Nombre de usuario invalido.");
        }
        if(pass.equals("") || pass.length()<4){
            JOptionPane.showMessageDialog(this, "Contraseña muy corta.");
        }else{
            //Registramos al usuario
            ClientUnicast.send("1<>"+name+"<>"+pass);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSesionMouseClicked
        this.dispose();
        ClientUnicast.stop();
        new login().setVisible(true);
    }//GEN-LAST:event_lblSesionMouseClicked

    private void lblLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblLoginMousePressed

    private void lblLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblLoginMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblP;
    private javax.swing.JPasswordField lblPassword;
    private javax.swing.JLabel lblSesion;
    private javax.swing.JLabel lblU;
    private javax.swing.JTextField lblUsername;
    // End of variables declaration//GEN-END:variables
}
